version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7

    working_directory: ~/gensim

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: build documentation
          command: |
            pip install tox
            tox -e docs -vv

      - save_cache:
          paths:
            - .tox/
          key: v1-dependencies-{{ checksum "setup.py" }}
