version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7

    working_directory: ~/gensim

    steps:
      - checkout
      - run:
          name: basic installation
          command: |
            python -m virtualenv venv
            source venv/bin/activate
            pip install tox

      - run:
          name: build documentation
          command: |
            source venv/bin/activate
            tox -e docs -vv
