version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7

    working_directory: ~/gensim

    steps:
      - checkout

      - restore_cache:
          key: pip-cache

      - run:
          name: install apt packages (for latex rendering)
          command: |
            sudo apt-get -yq update
            sudo apt-get -yq remove texlive-binaries --purge
            sudo apt-get -yq --no-install-suggests --no-install-recommends --force-yes install dvipng texlive-latex-base texlive-latex-extra texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended latexmk

      - run:
          name: basic installation
          command: |
            python -m virtualenv venv
            source venv/bin/activate
            pip install tox

      - run:
          name: build documentation
          command: |
            source venv/bin/activate
            tox -e docs -vv

      - save_cache:
          key: pip-cache
          paths:
            - "~/.cache/pip"
            - "~/.ccache"
            - "~/.pip-cache"
