version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7

    working_directory: ~/gensim

    steps:
      - checkout
      - run: basic installation
        command: |
          python -m venv venv
          . venv/bin/activate
          pip install tox

      - run:
          name: build documentation
          command: |
            pip install tox
            tox -e docs -vv
